/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar
 * - automatically sort documentation entries
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction/Setup',
      // The incorrect 'link' line is now REMOVED
      items: [{type: 'autogenerated', dirName: 'introduction'}], // This line finds all files inside 'introduction'
    },
    {
      type: 'category',
      label: 'Module 1: Foundation',
      // The incorrect 'link' line is now REMOVED
      items: [{type: 'autogenerated', dirName: 'module1'}],
    },
    {
      type: 'category',
      label: 'Module 2: Sensors & Perception',
      // The incorrect 'link' line is now REMOVED
      items: [{type: 'autogenerated', dirName: 'module2'}],
    },
    {
      type: 'category',
      label: 'Module 3: Control & Action',
      // The incorrect 'link' line is now REMOVED
      items: [{type: 'autogenerated', dirName: 'module3'}],
    },
    {
      type: 'category',
      label: 'Module 4: HRI & VLA',
      // The incorrect 'link' line is now REMOVED
      items: [{type: 'autogenerated', dirName: 'module4'}],
    },
  ],
};

module.exports = sidebars;